openapi: 3.0.0
info:
  title: annotation-competition-api
  version: '1.0'
servers:
  - url: 'http://annotation-competition.herokuapp.com/api/v1'
paths:
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example:
                  value:
                    id: 0
                    userName: string
                    email: user@example.com
                    userId: string
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                userName:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                  maxLength: 20
                  format: password
              required:
                - userId
                - userName
                - email
                - password
            examples:
              example-1:
                value:
                  userId: string
                  userName: string
                  email: user@example.com
                  password: pa$$word
          application/javascript:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties: {}
        description: Post the necessary fields for the API to create a new user.
      description: ユーザーを登録
  /user/login:
    post:
      summary: ''
      operationId: post-user-login
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
              examples:
                example:
                  value:
                    accessToken: string
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                password:
                  type: string
                  format: password
      description: ログイン操作を実施し，アクセストークンを取得
  /leader_board:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        userId:
                          type: string
                        userName:
                          type: string
                        annotationCount:
                          type: string
                        rank:
                          type: integer
              examples:
                example:
                  value:
                    users:
                      - userId: string
                        userName: string
                        annotationCount: string
                        rank: string
        '500':
          description: Internal Server Error
      operationId: get-leader_board
      parameters:
        - schema:
            type: string
          in: header
          name: 'Authorization: Token <AccessToken>'
          description: 認証のためのアクセストークン
      description: アノテーションコンペティションのリーダーボードの情報を取得（認証が必要）
  /competition/next:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  competitionId:
                    type: string
                    minLength: 1
                  competitionName:
                    type: string
                    minLength: 1
                  startAt:
                    type: string
                    minLength: 1
                  endAt:
                    type: string
                    minLength: 1
                  isRunning:
                    type: boolean
                required:
                  - competitionId
                  - competitionName
                  - startAt
                  - endAt
                  - isRunning
              examples:
                example:
                  value:
                    competitionId: string
                    competitionName: string
                    startAt: string
                    endAt: string
                    isRunning: true
        '500':
          description: Internal Server Error
      operationId: get-competition-next
      description: 開催中，もしくは次のコンペティションの情報を取得
  /competition/assignment:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  competitionId:
                    type: string
                    minLength: 1
                  images:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        imageId:
                          type: string
                          minLength: 1
                        imageUrl:
                          type: string
                          format: uri
                      required:
                        - imageId
                required:
                  - competitionId
                  - images
              examples:
                example:
                  value:
                    competitionId: string
                    images:
                      - imageId: string
                        imageUrl: 'http://example.com'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: get-competition-assignment
      description: アノテーションする画像などの情報を取得(認証が必要)
      parameters:
        - schema:
            type: string
          in: header
          name: 'Authorization: Token <AccessToken>'
          description: 認証のためのアクセストークン
    post:
      summary: ''
      operationId: post-competition-assignment
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: アノテーション結果を送信（認証が必要）
      parameters:
        - schema:
            type: string
          in: header
          name: 'Authorization: Token <AccessToken>'
          description: 認証のためのアクセストークン
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                competitionId:
                  type: string
                  minLength: 1
                annotations:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    required:
                      - imageId
                      - annotation
                    properties:
                      imageId:
                        type: string
                        minLength: 1
                      annotation:
                        type: string
                        minLength: 1
              required:
                - competitionId
                - annotations
            examples:
              example:
                value:
                  competitionId: string
                  annotations:
                    - imageId: string
                      annotation: string
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples: {}
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        userName:
          type: string
        email:
          type: string
          format: email
        userId:
          type: string
      required:
        - id
        - userName
        - email
        - userId
